local v = require("modules/vars")

hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl dispatch workspace 1")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,pkcs11,ssh")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("sh -c 'sleep 1; " .. v.home .. "/.local/bin/set-wallpaper'")
  hl.exec_cmd("waybar")
  hl.exec_cmd("dunst")
end)
